version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
    - 4.3.0-dev.20210428
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.14
    - 5.1.15
    - 5.1.16
    - 5.1.17
    - 5.1.18
    - 5.1.19
  - dependency-name: "@next/mdx"
    versions:
    - 10.0.6
    - 10.0.6-canary.9
    - 10.0.7
    - 10.0.7-canary.2
    - 10.0.7-canary.3
    - 10.0.7-canary.4
    - 10.0.7-canary.6
    - 10.0.7-canary.7
    - 10.0.7-canary.8
    - 10.0.8
    - 10.0.8-canary.11
    - 10.0.8-canary.14
    - 10.0.8-canary.15
    - 10.0.8-canary.17
    - 10.0.8-canary.5
    - 10.0.8-canary.6
    - 10.0.8-canary.7
    - 10.0.8-canary.8
    - 10.0.9
    - 10.0.9-canary.6
    - 10.0.9-canary.7
    - 10.1.2
    - 10.1.3
  - dependency-name: "@next/bundle-analyzer"
    versions:
    - 10.0.6
    - 10.0.6-canary.9
    - 10.0.7
    - 10.0.7-canary.2
    - 10.0.7-canary.3
    - 10.0.7-canary.4
    - 10.0.7-canary.6
    - 10.0.7-canary.7
    - 10.0.7-canary.8
    - 10.0.8
    - 10.0.8-canary.11
    - 10.0.8-canary.14
    - 10.0.8-canary.15
    - 10.0.8-canary.17
    - 10.0.8-canary.5
    - 10.0.8-canary.6
    - 10.0.8-canary.7
    - 10.0.8-canary.8
    - 10.0.9
    - 10.0.9-canary.6
    - 10.0.9-canary.7
    - 10.1.2
    - 10.1.3
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.0.6-canary.9
    - 10.0.7
    - 10.0.7-canary.2
    - 10.0.7-canary.3
    - 10.0.7-canary.4
    - 10.0.7-canary.6
    - 10.0.7-canary.7
    - 10.0.7-canary.8
    - 10.0.8
    - 10.0.8-canary.11
    - 10.0.8-canary.14
    - 10.0.8-canary.15
    - 10.0.8-canary.17
    - 10.0.8-canary.5
    - 10.0.8-canary.6
    - 10.0.8-canary.7
    - 10.0.8-canary.8
    - 10.0.9
    - 10.0.9-canary.6
    - 10.0.9-canary.7
    - 10.1.2
    - 10.1.3
  - dependency-name: husky
    versions:
    - 5.0.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: critters
    versions:
    - 0.0.10
    - 0.0.7
    - 0.0.8
    - 0.0.9
  - dependency-name: preact
    versions:
    - 10.5.12
    - 10.5.13
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
