language: dart
sudo: false
dart:
- dev
branches:
  only:
  - master
before_install:
- ". $HOME/.nvm/nvm.sh"
- nvm install node
- nvm use node
- yarn global add now@latest
dart_task:
- dartanalyzer: "--fatal-warnings ."
- dartfmt
cache:
  dart: true
  yarn: true
  directories:
  - "$HOME/.pub-cache"
  - node_modules
script:
- pub get
- yarn install
- yarn run build
- yarn run deploy
- yarn run alias
env:
  global:
    secure: GrSoLgRHahuVQ1eEiXt6yonR+HYNKpY64xUyMU2xEPHeM1eSUv+XJUVBAwL6Aiyylw8+48q2Mwrw/NZaJSKrgfDojWdzKM3q7xf7qGpWZVC4DbHiL4G5zmLjY43Mq0FyQRsGMFHo7SAXLHFy3jyMmGMPk9rA9ScZvf+IbGm/6fRFcpiIYUTp/czbeoIJnwc8bEPqjIKat1zl0nfSXPEi/QFgQ2aDdFlVANQ5a3AwfwmaTnKeYwDanW9blcizYMbzUW2YuTJwgcU2BrwzWcpyFIKnhJEvmcSWaO9cgQkCUjShTm5IfPJAOEx/xCxwB8lZEPeHc6gBUhnnEWG9ls+konOYzw33IGtv8Pz/z3W8GHRIuuVrQl9shZgLIfZV9XjbmwPPQT0UsJWJRhGT9VIk7pxbKQJEcOtTxbRnHt6lZbgu+hxb5FUOyaKs5RAZyyTCgnmgKC5cE/njvnlCvkVpB1h1jcmtiwBEAty3b4F5pPXYTptV5gYkdFb5R1aaCWlbbgeyqQj5XXdj9140fWO8B5TSOqlvQsLNEyhLS1NsA8yywr7qxgo9jGUQJj410yuaDT0HW+gvnEu+i4459CMyzIPpN/pgvnyiEBIJ62Qzv9UzSJ+RT5SrUaA7TvLXv+y2H1X3Anb2t7O59ZSZ5WeF5vZUdrJ7l2hzK6Mz57LovMI=
