language: dart

sudo: false

dart:
  - dev

branches:
  only:
    - master
  
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install node
  - nvm use node

dart_task:
  - dartanalyzer: --fatal-warnings .
  - dartfmt

cache:
- dart
- yarn
  directories:
    - $HOME/.pub-cache
    - node_modules

script:
  - pub get
  - yarn install
  - yarn run build

deploy:
  provider: firebase
  token:
    secure: RrkjKAKp8/z2VeqL8PVSjjbnIxgHyLbb6bYZzTVKvZPgX9rt1n32MGs8kgqeyF6Ju4bsrOyBuhWYp2dudn8oFSnJiHvMpnNyBfCcnZw5j5IEdyVnMq1hCThgqQ+C4sV/24LYH001y2Xys4Zxwa+wknytiJeg6O9jNhQh+tw1ap9vNLyzXeSzdVpfQUFGhlFIPlQnalRRUYbLUC/oQjSKm6ZpASQaLh87iM6EyjByBk2K1x+MkdY8OsrrPxuFCGdZFoMp/CzaXcvkqJ8l1n3RSjqYFgGNeMXLJ1QueUb9s+c9tVtoQ3GdHYY3pFvDKTqoWTw81k5928wMdl6JpNKcNuvy0OGkQUDBsMQlCYJfuLGRAzjGMS0RgcqdIe9bSXltdguecltuckxTKa+0h2VLCZrQyhei5gQDuP0VMa729qyr/FgbJ4Hm399rm6OQj+FUaypt4J71ByJhy2YOIL0izJMgl3bGAQLSpwogkLFZ5iqi61m9nfmxQ9Z8dmmpyAS2WtAgPy6jR3W/ihm8fFf2cqLa5y60D44chNBXo/QSFRHKIOr5Wc4H/Kr+IMbEJDbemVp7stCqMSpAOk8dz1VuAJGc26m7DdVDkTduGeTbrEZzXswEFM73IveAc4DI0iBoxchEGeQO15tUj8c+ZfecGHcF9xfuQ1TIRJ4JepxCEBY=
