language: dart
sudo: false
dart:
- dev
branches:
  only:
  - master
before_install:
- ". $HOME/.nvm/nvm.sh"
- nvm install node
- nvm use node
dart_task:
- dartanalyzer: "--fatal-warnings ."
- dartfmt
cache:
  dart: true
  yarn: true
  directories:
  - "$HOME/.pub-cache"
  - node_modules
script:
- pub get
- yarn install
- yarn run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: RpF/dXDMSminEYXqcU7gXCw3orhGYm4yng7P1Wof2Zd5Cj3iXy+m8NxgjaHWEhRJ36WHjnNPCh6ZZxDC57+UorlNZhAs71Fo9hOYhwE+GPWaHjbJOos9kNcPGEcYtQUYbIQN9xGPWZXb9cpNZGqwhyOP+yiCbYZl8UFmpHxEkwdQ8DLN1gtTFRT57Vm2fgUcBSjr5DRbb9n+rX6lsmyJ5JjU0ZN6qiFSFAs9lAS42KIP7QHPArZRteYTYK2QEinhFxa/QNN1SBoqaXhQPG9acKfaoZROgqo64tGdbMGJyzZWVtzRfxKbZ3J32TS1cjWXgFqWqYPB5bSXWc8tYxV0VAapLJp1LuoAZUccFAUpXSJaXwqc7YQszktbQJwu7yj6tOuT3RGjPooLuDx90oxlhs3+iel7fj0npwHoYoWaZcuaqExGWG7OnUfwCgCTuujRa0nJZVEGIIsNpjE0o/UWXfz78Ll1XJAkGHZhoV2jxe3PmP8twNMU6/CbOXH7Zv3ro7xxj/1tMSOWO73UTeXEYIJwJvgMbrFUd2eeh44okDyJW/PFbYeBQ+lMUiRRjYdChiWaLT00teTLlamhbtvF1k9pO7Fb0sksiHiB3HB2X8loGZKXe4hRCSDH7MnlG72zNQPnujayu6DI/vWMzhnfmk0wt3ZqAe0QBFBnzV0zAUY=
