targets:
  website:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - web/**.dart
        options:
          compiler: dart2js
          dart2js_args:
          - --csp
          - --enable-diagnostic-colors
          - --fast-startup
          - --minify
          - --trust-primitives
          - --trust-type-annotations
