name: website
description: Personal site built with Dart, Angular, and Firebase
version: 0.0.1
homepage: https://anthony.codes
author: Anthony Maki (https://anthony.codes) <4cm4k1@gmail.com>

environment:
  sdk: '>=2.0.0-dev <=2.0.0'

dependencies:
  angular: ^5.0.0-alpha+9
  angular_components: ^0.9.0-alpha+9
  angular_forms: ^2.0.0-alpha+1
  angular_router: ^2.0.0-alpha+9
  firebase: ^4.4.0
  pwa: ^0.1.10

dev_dependencies:
  angular_ast: ^0.5.0
  angular_compiler: ^0.4.0-alpha+9
  angular_test: ^2.0.0-alpha+7
  build_runner: ^0.8.1
  build_web_compilers: ^0.3.5
  sass_builder: ^1.1.5
  test: ^0.12.33

dependency_overrides:
  angular:
    git:
      url: https://github.com/dart-lang/angular.git
      path: angular

license: MIT
