name: website
description: Personal site built with Dart, Angular, and Firebase
version: 0.0.1
homepage: https://anthony.codes
author: Anthony Maki (https://anthony.codes) <4cm4k1@gmail.com>

environment:
  sdk: '>=2.0.0-dev <=2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  angular_forms: ^2.0.0-beta
  angular_router: ^2.0.0-alpha+15
  firebase: ^5.0.0-beta
  pwa: ^0.1.10

dev_dependencies:
  angular_ast: ^0.5.3+3
  angular_compiler: ^0.4.0-alpha+16
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.1
  build_web_compilers: ^0.4.0+4
  sass_builder: ^2.1.0
  test: ^1.2.0

license: MIT
