name: website
description: Personal site built with Dart, Angular, & Firebase
version: 1.0.0
homepage: https://anthony.codes
author: Anthony Maki <4cm4k1@gmail.com>

environment:
  sdk: '<=2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  angular_router: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^1.0.1
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.3
  test: ^0.12.26

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
 compiler:
   debug: dartdevc
