name: website
description: Personal site built with Dart, Angular, and Firebase
version: 0.0.1
homepage: https://anthony.codes
author: Anthony Maki (https://anthony.codes) <4cm4k1@gmail.com>

environment:
  sdk: '>=2.0.0-dev <=2.0.0'

dependencies:
  angular: ^5.0.0-beta+2
  angular_components: ^0.9.0-beta+1
  angular_forms: ^2.0.0-beta+2
  angular_router: ^2.0.0-alpha+17
  firebase: ^5.0.1
  pwa: ^0.1.10

dev_dependencies:
  angular_ast: ^0.5.4
  angular_compiler: ^0.4.0-alpha+18
  angular_test: ^2.0.0-beta+2
  build_runner: ^0.9.2
  build_web_compilers: ^0.4.1
  sass_builder: ^2.1.1
  test: ^1.3.0

license: MIT
