name: website
description: Personal site built with Dart, Angular, and Firebase
version: 0.0.1
homepage: https://anthony.codes
author: Anthony Maki (https://anthony.codes) <4cm4k1@gmail.com>

environment:
  sdk: '>=2.0.0-dev <=2.0.0'

dependencies:
  angular: ^5.0.0-alpha+6
  angular_components: ^0.9.0-alpha+6
  angular_forms: ^1.0.1-alpha+6
  angular_router: ^2.0.0-alpha+6
  firebase: ^4.3.1

dev_dependencies:
  angular_ast: ^0.4.3
  angular_compiler: ^0.4.0-alpha+6
  angular_test: ^2.0.0-alpha+4
  browser: ^0.10.0+2
  build_runner: ^0.7.11+1
  build_web_compilers: ^0.3.1
  sass_builder: ^1.1.4
  test: ^0.12.31

license: MIT
