name: website
description: Personal site built with Dart, Angular, and Firebase
version: 0.0.1
homepage: https://anthony.codes
author: Anthony Maki (https://anthony.codes) <4cm4k1@gmail.com>

environment:
  sdk: '>=2.0.0-dev <=2.0.0'

dependencies:
  angular: ^5.0.0-alpha+15
  angular_components: ^0.9.0-alpha+15
  angular_forms: ^2.0.0-alpha+7
  angular_router: ^2.0.0-alpha+14
  firebase: ^4.5.1
  pwa: ^0.1.10

dev_dependencies:
  angular_ast: ^0.5.3+3
  angular_compiler: ^0.4.0-alpha+15
  angular_test: ^2.0.0-alpha+13
  build_runner: ^0.8.10
  build_web_compilers: ^0.4.0+4
  sass_builder: ^2.0.3
  test: ^0.12.42

license: MIT

# dependency_overrides:
#   angular_components:
#     git:
#       url: https://github.com/dart-lang/angular_components.git
#       ref: github-sync
#   build_config: ^0.3.0
