name: website
description: Personal site built with Dart, Angular, and Firebase
version: 0.0.1
homepage: https://anthony.codes
author: Anthony Maki (https://anthony.codes) <4cm4k1@gmail.com>

environment:
  sdk: '>=2.0.0-dev <=2.0.0'

dependencies:
  angular: ^5.0.0-alpha+7
  angular_components: ^0.9.0-alpha+7
  angular_forms: ^1.0.1-alpha+7
  angular_router: ^2.0.0-alpha+7
  firebase: ^4.4.0
  pwa: ^0.1.9+1

dev_dependencies:
  angular_ast: ^0.4.3+1
  angular_compiler: ^0.4.0-alpha+7
  angular_test: ^2.0.0-alpha+5
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.4+1
  sass_builder: ^1.1.4
  test: ^0.12.32+1

license: MIT
